### ISSUE TITLE
about preprocess.py file

### ISSUE THREAD

**Issue by Nero0113** [lancopku/MUKI#1]
this file is  incomplete

**Comment by TobiasLee** [comment]
Hi, could you be more specific on the problem? Did you encounter any errors in running the experiment? If so, could you please provide more contexts so I can help.

**Comment by Nero0113** [comment]
> Hi, could you be more specific on the problem? Did you encounter any errors in running the experiment? If so, could you please provide more contexts so I can help.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/94276947/225031142-2bb10e6d-2e99-4fda-9523-16507e3cba48.png">
The code for data pre-processing may not be complete. The input of run_glue.py should be a csv file, or you can tell me what the format of the input data is.
